version: '3.4'

services:
  twosum_enterprise:
    image: ${DOCKER_REGISTRY-}twosumenterprise
    build:
      context: .
      dockerfile: TwoSum_Enterprise/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on:
      - postgresdb
      - rabbitmq
    ports:
      - "5000:8080"

  postgresdb:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123321
      POSTGRES_DB: twosumdb
    ports:
      - "5432:5432"
    # volumes:
    #   - postgres_data:/var/lib/postgresql/data

  rabbitmq:
    image: rabbitmq:management
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    ports:
      - "5672:5672"
      - "15672:15672"

# volumes:
#   postgres_data:
